version: '3'

tasks:
  setup:
    - pnpm i
    - uv sync
    - uv run scripts/link-ida.py

  build:
    - uv run scripts/check-css.py
    - uv run scripts/build-css.py
    - uv run scripts/build-icons.py
    - uv run scripts/build.py

  install:
    - task: build
    - uv run scripts/install.py

  clean:
    - rm -rf dist
    - rm -rf .cache
    - rm -rf .venv
    - pnpm clean
