"""
Runs inside IDA (started headless by scripts/dump-icons.py): write the icons
IDA's actions can show to src/ida/icon_meta.yaml, then quit.

IDA's icon table holds its Qt resource images, keyed by path without the
`:/<prefix>/` (:/IDAG/resources/menu/AddConst.svg is
resources/menu/AddConst.svg); get_icon_id_by_name() knows these, so the
plugin maps them at runtime by path. Icons outside the table (loaded at
runtime without a name, e.g. the Git actions') can only be matched by the
actions showing them; they get the path action_ids/<id>.svg.

Also writes .cache/ida-icon-dump/: svg/<key> (the table's icons),
untabled/<path> (the other resource images, e.g. the Git icons' originals)
and icons.txt (menu icon names, :/IDAG/resources/menu/<Name>.svg, not
numbered); error.txt there if something failed.

Only meaningful with the catppuccin plugin off (it replaces action icons);
dump-icons starts IDA with CATPPUCCIN_DISABLE=1 for that.
"""

import os
import shutil
import traceback
from collections import defaultdict
from pathlib import Path

import ida_kernwin
import ida_pro
from PySide6.QtCore import QDirIterator, QFile, QIODevice

ROOT = Path(__file__).resolve().parents[2]
META_FILE = ROOT / "src" / "ida" / "icon_meta.yaml"
OUT_DIR = ROOT / ".cache" / "ida-icon-dump"
MENU_PREFIX = ":/IDAG/resources/menu/"
IMAGE_SUFFIXES = (".svg", ".png")
QT_OWN_PREFIX = ":/qt-project.org/"     # Qt's own style images
UNNAMED_PATH = "action_ids/%d.svg"

HEADER = """\
# Icons IDA's actions can show. Generated by scripts/ida/dump_icons.py
# (IDA %s) -- regenerate with ./x dump-icons rather than edit.
#
# - path: where the theme's version is, under themes/catppuccin/. For icons
#   in IDA's icon table it is the Qt resource path without `:/<prefix>/`
#   (IDAG, HVUI, ...), which the plugin finds at runtime. Sorted by path.
# - actions: the actions showing it when dumped.
# - map_by_action: true for icons IDA loads without a name (nothing maps
#   their id back to a file): the plugin matches the actions instead, and
#   the path is action_ids/<id>.svg (the id when dumped; only a file name).
"""


def resource_images():
    """Every image path in the Qt resources (:/...), sorted."""
    paths = []
    it = QDirIterator(":/", QDirIterator.IteratorFlag.Subdirectories)
    while it.hasNext():
        path = it.next()
        if path.endswith(IMAGE_SUFFIXES):
            paths.append(path)
    return sorted(paths)


def table_key(path):
    """:/<prefix>/<key> -> <key>, the way IDA's load_icon() names icons."""
    parts = path[len(":/"):].split("/", 1)
    return parts[1] if len(parts) == 2 else None


def icon_table(paths):
    """{id: (key, resource path)} for the resources IDA's icon table knows by key."""
    table = {}
    for path in paths:
        key = table_key(path)
        icon_id = ida_kernwin.get_icon_id_by_name(key) if key else -1
        if icon_id >= 0:
            table.setdefault(icon_id, (key, path))
    return table


def copy_resource(path, target):
    f = QFile(path)
    f.open(QIODevice.OpenModeFlag.ReadOnly)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(f.readAll().data())


def yaml_str(text):
    """A YAML scalar: plain when safe, else double-quoted."""
    if text and all(c.isalnum() or c in "/._-:" for c in text) and not text[0].isdigit() \
            and not text.endswith(":"):
        return text
    return '"%s"' % text.replace("\\", "\\\\").replace('"', '\\"')


def yaml_list(items):
    return "[%s]" % ", ".join(yaml_str(i) for i in items)


def dump():
    paths = resource_images()
    table = icon_table(paths)
    tabled = set(path for _, path in table.values())

    entries = {}                       # path -> (map_by_action, [action])
    for key, _ in table.values():
        entries[key] = (False, [])     # also icons no action shows (e.g. window icons)
    for name in ida_kernwin.get_registered_actions():
        ok, icon_id = ida_kernwin.get_action_icon(name)
        if not ok or icon_id < 0:
            continue
        if icon_id in table:
            entries[table[icon_id][0]][1].append(name)
        else:
            entries.setdefault(UNNAMED_PATH % icon_id, (True, []))[1].append(name)

    lines = [HEADER % ida_kernwin.get_kernel_version()]
    for path in sorted(entries):
        by_action, actions = entries[path]
        lines.append("- path: %s" % yaml_str(path))
        if by_action:
            lines.append("  map_by_action: true")
        lines.append("  actions: %s" % yaml_list(sorted(actions)))
    META_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")

    # Paths drop the `:/<prefix>/`; two resources differing only in prefix
    # would share a theme file.
    by_key = defaultdict(list)
    for path in paths:
        if not path.startswith(QT_OWN_PREFIX) and table_key(path):
            by_key[table_key(path)].append(path)
    clashes = ["%s is the path of %s" % (key, ", ".join(c)) for key, c in sorted(by_key.items()) if len(c) > 1]

    for key, path in table.values():
        copy_resource(path, OUT_DIR / "svg" / key)
    for path in paths:
        if path not in tabled:
            copy_resource(path, OUT_DIR / "untabled" / path[len(":/"):])
    names = [p[len(MENU_PREFIX):] for p in paths if p.startswith(MENU_PREFIX)
             and "/" not in p[len(MENU_PREFIX):] and p.endswith(".svg")
             and not p[len(MENU_PREFIX):-len(".svg")].isdigit()]
    (OUT_DIR / "icons.txt").write_text("".join(n + "\n" for n in names), encoding="utf-8", newline="\n")
    (OUT_DIR / "summary.txt").write_text(
        "".join(line + "\n" for line in [
            "%d icons in the table, %d unnamed (map_by_action)"
            % (len(table), sum(1 for by_action, _ in entries.values() if by_action))] + clashes),
        encoding="utf-8", newline="\n")


try:
    if OUT_DIR.exists():
        shutil.rmtree(OUT_DIR)
    OUT_DIR.mkdir(parents=True)
    if os.environ.get("CATPPUCCIN_DISABLE") != "1":
        raise RuntimeError("run through ./x dump-icons (CATPPUCCIN_DISABLE=1 keeps the "
                           "catppuccin plugin from replacing the icons being dumped)")
    dump()
except Exception:
    (OUT_DIR / "error.txt").write_text(traceback.format_exc(), encoding="utf-8")
finally:
    ida_pro.qexit(0)
