"""
Bundle the plugin sources in src/ into a single file.

    uv run scripts/build-py.py    -> dist/catppuccin-ida/plugins/catppuccin.py

(The theme CSS is built by scripts/build-css.py.)

src/main_ida.py is the entry point; tools/python_bundler.py inlines the src
modules it imports (src/ida/<name>.py is `ida.<name>`). Rules for src/, so the
flattened file behaves like the modules did:
- import src modules as `from module import name` (`from ida.chrome import
  Chrome`), never `import module`
- top-level names must be unique across all src modules
"""

from common.errors import run
from common.paths import DIST_PLUGIN, rel, src_module
from tools.python_bundler import Guard, bundle_python_modules

ENTRY = "main_ida"
# Modules generated by other scripts (src/color_gen.py by build-css,
# src/ida/icon_meta_gen.py by build-icons)
GENERATED_SUFFIX = "_gen"
HEADER = "# Generated by scripts/build-py.py from src/ -- edit the sources, not this file."


# The plugin only runs in IDA's GUI: text-mode IDA and idalib refuse to import
# PySide6 ("PySide6 can only be used from the GUI version of IDA"), so the
# whole bundle sits under is_idaq(); there, a plugin that skips quietly.
GUI_ONLY = Guard(
    imports="import ida_idaapi\nimport ida_kernwin",
    condition="ida_kernwin.is_idaq()",
    fallback='''
class CatppuccinHeadless(ida_idaapi.plugin_t):
    """No GUI to theme (text-mode IDA, idalib): skip."""
    flags = ida_idaapi.PLUGIN_HIDE
    comment = "Catppuccin (GUI only)"
    help = ""
    wanted_name = "Catppuccin"
    wanted_hotkey = ""

    def init(self):
        return ida_idaapi.PLUGIN_SKIP

    def run(self, arg):
        pass

    def term(self):
        pass


def PLUGIN_ENTRY():
    return CatppuccinHeadless()
''')


def _missing_hint(module):
    if module.endswith(GENERATED_SUFFIX):
        return "src/%s.py is generated; run ./x build-css and ./x build-icons first" % module
    return None


def build_plugin():
    bundle = bundle_python_modules(src_module(ENTRY), HEADER, _missing_hint, GUI_ONLY)
    DIST_PLUGIN.parent.mkdir(parents=True, exist_ok=True)
    DIST_PLUGIN.write_text(bundle.source, encoding="utf-8", newline="\n")
    print("built %s from %s" % (rel(DIST_PLUGIN), ", ".join(rel(p) for p in bundle.modules)))


if __name__ == "__main__":
    run(build_plugin)
