"""
Build the theme: generate the colour definitions and bundle the CSS.

    uv run scripts/build-css.py    -> dist/catppuccin-ida/themes/catppuccin/theme.css
                                      src/color_gen.py

1. Definitions are generated from the config file (common.paths.CONFIG_FILE):
   `@importtheme "_base";` then an @def for every colour (ctp-c-*),
   definition (ctp-d-*) and role (ctp-r-*).
2. The CSS files listed in src/styles.txt are appended in that order.
3. IDA's toolbar/menu icons (src/icons.txt) are pointed at the theme's own
   icons/menu/<Name>.svg (built by scripts/build-icons.py).
4. The roles the plugin needs (common.config.ROLE_TARGETS) are written to
   src/color_gen.py as resolved colours, e.g. TITLEBAR__CAPTION = "#181825".
"""

from common.config import HEX_RE, PYTHON, colors, definitions, load_config, resolve, roles
from common.errors import ScriptError, run
from common.paths import COLOR_GEN, CONFIG_FILE, ICON_LIST, STYLES_LIST, THEME_CSS, ida_icon_names, rel
from tools.css_bundler import bundle_css_files, css_banner

# IDA expands variable references even inside comments, so nothing written into
# a comment here may contain a dollar-brace sequence.
HEADER = """/*
 * Catppuccin for IDA.
 *
 * Generated by scripts/build-css.py -- edit %s and src/, not this file.
 *
 * Colours are layered:
 *   ctp-c-*   palette colours and tints
 *   ctp-d-*   definitions: shared aliases of colours
 *   ctp-r-*   roles: one per place a colour is used below
 *
 * Pseudocode needs the catppuccin plugin (src/hexrays.py): Hex-Rays reuses
 * one colour tag for keywords and numbers, one for members and operators,
 * and so on; the plugin re-tags its output so each kind gets its own.
 */"""


def _defs(names_values, prefix):
    width = max(len(n) for n, _ in names_values) + len(prefix)
    return "\n".join("@def %-*s %s;" % (width, prefix + n, v) for n, v in names_values)


def _ref(ref):
    """`c-green` -> the CSS reference to ctp-c-green."""
    return "${ctp-%s}" % ref


def generate_python(config, color_values, definition_values):
    """src/color_gen.py: the plugin's roles as resolved colours."""
    lines = ['"""Colours used by the plugin.',
             "",
             "Generated by scripts/build-css.py from %s -- do not edit." % rel(CONFIG_FILE),
             '"""', ""]
    for name, ref in roles(config, color_values, definition_values, PYTHON):
        value = resolve(ref, color_values, definition_values)
        if not HEX_RE.fullmatch(value):
            raise ScriptError("%s: roles.%s resolves to %s; the plugin needs an opaque #rrggbb colour"
                              % (rel(CONFIG_FILE), name.replace("--", "."), value))
        constant = name.replace("-", "_").upper()
        lines.append('%s = "%s"  # %s' % (constant, value, ref))
    return "\n".join(lines) + "\n"


def generate_definitions(config, color_values, definition_values):
    role_values = roles(config, color_values, definition_values)
    parts = [
        HEADER % rel(CONFIG_FILE),
        '@importtheme "_base";',
        css_banner("Colours (palette and tints)") + "\n\n"
        + _defs(list(color_values.items()), "ctp-c-"),
        css_banner("Definitions") + "\n\n"
        + _defs([(n, _ref(v)) for n, v in definition_values.items()], "ctp-d-"),
        css_banner("Roles") + "\n\n"
        + _defs([(n, _ref(v)) for n, v in role_values], "ctp-r-"),
    ]
    return "\n\n".join(parts)


def generate_menu_icons():
    """Point every IDA toolbar/menu icon at icons/menu/<Name>.svg."""
    lines = ['    qproperty-themeicon-%s: url("$RELPATH/icons/menu/%s.svg");' % (n, n)
             for n in ida_icon_names()]
    return "%s\n\nIDAMainWindow\n{\n%s\n}" % (
        css_banner("Toolbar/menu icons (generated from %s)" % rel(ICON_LIST)), "\n".join(lines))


def main():
    config = load_config()
    color_values = colors(config)
    definition_values = definitions(config, color_values)

    styles = bundle_css_files(STYLES_LIST)
    parts = [generate_definitions(config, color_values, definition_values),
             styles.source,
             generate_menu_icons()]
    output = "\n\n".join(parts) + "\n"

    THEME_CSS.parent.mkdir(parents=True, exist_ok=True)
    THEME_CSS.write_text(output, encoding="utf-8", newline="\n")
    print("built %s from %s, %s, %s" % (rel(THEME_CSS), rel(CONFIG_FILE),
                                        ", ".join(rel(p) for p in styles.files), rel(ICON_LIST)))

    python = generate_python(config, color_values, definition_values)
    COLOR_GEN.write_text(python, encoding="utf-8", newline="\n")
    print("built %s from %s" % (rel(COLOR_GEN), rel(CONFIG_FILE)))


if __name__ == "__main__":
    run(main)
