"""
Bundle the plugin sources in src/ into a single file.

    uv run scripts/build-py.py    -> dist/catppuccin-ida/plugins/catppuccin.py

(The theme CSS is built by scripts/build-css.py.)

src/main.py is the entry point; tools/python_bundler.py inlines the src
modules it imports. Rules for src/, so the flattened file behaves like the
modules did:
- import src modules as `from module import name`, never `import module`
- top-level names must be unique across all src modules
"""

from common.errors import run
from common.paths import DIST_PLUGIN, rel, src_module
from tools.python_bundler import bundle_python_modules

ENTRY = "main"
# Modules generated by other scripts (src/color_gen.py by build-css,
# src/icons_gen.py by build-icons)
GENERATED_SUFFIX = "_gen"
HEADER = "# Generated by scripts/build-py.py from src/ -- edit the sources, not this file."


def _missing_hint(module):
    if module.endswith(GENERATED_SUFFIX):
        return "src/%s.py is generated; run ./x build-css and ./x build-icons first" % module
    return None


def build_plugin():
    bundle = bundle_python_modules(src_module(ENTRY), HEADER, _missing_hint)
    DIST_PLUGIN.parent.mkdir(parents=True, exist_ok=True)
    DIST_PLUGIN.write_text(bundle.source, encoding="utf-8", newline="\n")
    print("built %s from %s" % (rel(DIST_PLUGIN), ", ".join(rel(p) for p in bundle.modules)))


if __name__ == "__main__":
    run(build_plugin)
