"""
Build the theme: generate the colour definitions and bundle the CSS.

    uv run scripts/build-css.py    -> dist/themes/catppuccin/theme.css

1. Definitions are generated from the constants file (common.paths.CONST_FILE):
   `@importtheme "_base";` then an @def for every colour (ctp-c-*),
   definition (ctp-d-*) and role (ctp-r-*).
2. The CSS files listed in src/styles.txt are appended in that order.
"""

import os

from common.const import colors, definitions, load_const, roles
from common.errors import run
from common.paths import CONST_FILE, DIST, rel
from common.styles import style_list, style_path

OUT = os.path.join(DIST, "themes", "catppuccin", "theme.css")
RULE = "-" * 66

# IDA expands variable references even inside comments, so nothing written into
# a comment here may contain a dollar-brace sequence.
HEADER = """/*
 * Catppuccin for IDA.
 *
 * Generated by scripts/build-css.py -- edit %s and src/, not this file.
 *
 * Colours are layered:
 *   ctp-c-*   palette colours and tints
 *   ctp-d-*   definitions: shared aliases of colours
 *   ctp-r-*   roles: one per place a colour is used below
 *
 * Pseudocode needs the catppuccin plugin (src/hexrays.py): Hex-Rays reuses
 * one colour tag for keywords and numbers, one for members and operators,
 * and so on; the plugin re-tags its output so each kind gets its own.
 */"""


def _banner(title):
    return "/* %s *\n * %s\n * %s */" % (RULE, title, RULE)


def _defs(names_values, prefix):
    width = max(len(n) for n, _ in names_values) + len(prefix)
    return "\n".join("@def %-*s %s;" % (width, prefix + n, v) for n, v in names_values)


def _ref(ref):
    """`c-green` -> the CSS reference to ctp-c-green."""
    return "${ctp-%s}" % ref


def generate_definitions():
    const = load_const()
    color_values = colors(const)
    definition_values = definitions(const, color_values)
    role_values = roles(const, color_values, definition_values)
    parts = [
        HEADER % rel(CONST_FILE),
        '@importtheme "_base";',
        _banner("Colours (palette and tints)") + "\n\n"
        + _defs(list(color_values.items()), "ctp-c-"),
        _banner("Definitions") + "\n\n"
        + _defs([(n, _ref(v)) for n, v in definition_values.items()], "ctp-d-"),
        _banner("Roles") + "\n\n"
        + _defs([(n, _ref(v)) for n, v in role_values], "ctp-r-"),
    ]
    return "\n\n".join(parts)


def main():
    parts = [generate_definitions()]
    paths = style_list()
    for path in paths:
        with open(style_path(path), encoding="utf-8") as f:
            css = f.read().strip("\n")
        parts.append("%s\n\n%s" % (_banner("src/" + path), css))
    output = "\n\n".join(parts) + "\n"

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(output)
    print("built %s from %s, %s" % (rel(OUT), rel(CONST_FILE),
                                    ", ".join("src/" + p for p in paths)))


if __name__ == "__main__":
    run(main, "build-css")
